version: "3.7"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Bangkok
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
